
#-------------HCHP---------------
utility_meter:
  #HC daily meter
  today_hc_meter:
    source: sensor.linky_hc
    cycle: daily
  #HP daily meter
  today_hp_meter:
    source: sensor.linky_hp
    cycle: daily
    
    
    
    
#-------------BASE---------------
utility_meter:
  #BASE daily meter
  today_base_meter:
    source: sensor.linky_base
    cycle: daily
