esphome:
  name: esp-linky
  platform: ESP8266
  board: d1_mini

#setup Wifi
wifi:
  ssid: "Wifi"
  password: "Password"

captive_portal:
logger:
  baud_rate: 0   # disable logging via UART, help to avoid numerous crash with ESP_LOGD
  level: INFO  # INFO for less log, put DEBUG to view all the linky's received info in the logs
  esp8266_store_log_strings_in_flash: False


api:
ota:


#setup uart between the linky and the ESP
uart:
  id: uart0
  rx_pin: GPIO3 #RX pin of wemos D1 Mini
  tx_pin: GPIO1
  baud_rate: 1200
  parity: EVEN
  data_bits: 7


#setup teleinfo, update value every 60s
teleinfo:
  id: myteleinfo
  update_interval: 60s
  historical_mode: true


sensor:
  #Linky BASE value
  - platform: teleinfo
    tag_name: "BASE"
    name: "Linky BASE"
    teleinfo_id: myteleinfo
    state_class: "total_increasing"
    device_class: "energy"
    unit_of_measurement: "Wh"

  #Linky Consumption
  - platform: teleinfo
    tag_name: "PAPP"
    name: "Linky Consommation"
    unit_of_measurement: "VA"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    
   #Linky Intensity
  - platform: teleinfo
    tag_name: "IINST"
    name: "Linky Intensité"
    unit_of_measurement: "A"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    
text_sensor:
  - platform: teleinfo
    tag_name: "OPTARIF"
    name: "optarif"
    teleinfo_id: myteleinfo
